////////////////////////////////////////////////////////////////////////
//
// Mapping.h
//
// This file was generated by MapForce 2023r2.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////


#ifndef Mapping_H_INCLUDED
#define Mapping_H_INCLUDED

#pragma once

#include "Resource.h"

#endif // Mapping_H_INCLUDED
