////////////////////////////////////////////////////////////////////////
//
// vmf_vmf3_entretorsultat.cpp
//
// This file was generated by MapForce 2023r2.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////


#include "StdAfx.h"
#include "Resource.h"
using namespace std;
#include "vmf_vmf3_entretorsultat.h"




#ifdef _DEBUG
	#define new DEBUG_NEW
	#undef THIS_FILE
	static char THIS_FILE[] = __FILE__;
#endif
namespace vmf 
{
	vmf3_entretorsultat::vmf3_entretorsultat()
	{
		hash[string_type(_T("9"))] = string_type(_T("104777"));
	}
} // namespace vmf 
